<?php
	#CONEXÃO COM O BANCO DE DADOS
	define('DB_HOST', '127.0.0.1');
	define('DB_USER', 'root');
	define('DB_PASS', '');
	define('DB_DATA', 'mextv3');
	
	#NA STRING ABAIXO FICA OS PLAYERS QUE NÃO PODEM LOGAR
	#PODE ACRESCENTAR MAIS NOMES NA LISTA
	#TODOS TEM QUE FICAR SEPARADOS POR VÍRUGA E SEM ESPAÇOS ENTRE AS VIRGULAS E O NOME
	$locked = "";
?>