/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2014 VigLink. Rights reserved and patent(s) pending.
*/
(function(k){var g,b={_breaker:{},each:function(a,c){var d,e;if("object"===b.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&c(a[d],d)===b._breaker)break}else if(a){d=0;for(e=a.length;d<e&&c(a[d],d)!==b._breaker;d++);}},extend:function(a){var c,d,b,f,h=arguments.length;a=a||{};for(d=1;d<h;d++)if(f=arguments[d],void 0!==f&&null!==f)for(b in f)c=f[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(a,d){try{return("function"===typeof window[d]||"object"===
typeof window[d])&&a instanceof window[d]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":c==c.window?"window":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},
attrValues:function(a,c,d){return(c=a[c])?c.split(d||" "):[]},batchable:function(a){a=b.extend({batch:b.noop,single:b.noop,timeout:100},a);var c=[],d=b.traits.cors&&b.traits.json,e=null,f=function(){null!==e&&(clearTimeout(e),e=null);1===c.length?a.single.apply(this,c[0]):1<c.length&&a.batch(c);c=[]},h=function(){c.push(b.toArray(arguments));null===e&&(e=setTimeout(b.bind(function(){f()},this),a.timeout))};b.extend(h,{flush:f,now:a.single});return d?h:a.single},bind:function(a,c){return function(){return a.apply(c,
arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),d=0;return function(b,f,h){if(b){var m=b[c];if(m||void 0!==h)return m||(m=++d),a[m]||(b[c]=m,a[m]={}),void 0!==h&&(a[m][f]=h),"string"===typeof f?a[m][f]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return b.extend({},a)},contains:function(a,c){return-1!==b.indexOf(a,c)},context:function(a){"element"===
b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,c){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,d===c)return!0;return!1},cors:function(a,c,d){var b,f=function(){d?d(b.responseText):eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===
b.status&&f()};try{return b.open("POST",a),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.withCredentials=!0,b.send(c),!0}catch(h){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var f;a=(e||document).createElement(a);c=c||{};d=d||{};for(f in c)void 0!==c[f]&&(a[f]=c[f]);b.css(a,d);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(e){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||
(e=a.apply(null,arguments),b=!0);return e}}(a)},escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(e){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,
arguments)}}}(),find:function(a,c){var d;b.each(a,function(a,f){if(c(a,f))return d=a,b._breaker});return d},generateNodeFilter:function(){var a=function(a,b){var f,h;b=","+b.join(",")+",";f=0;for(h=a.length;f<h;f++)if(c(a[f],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,f){f=b.extend({ancestors:!0,self:!0},f);var h=!0,m=
!0,g=function(e,f){var h;if(h=!(d.tags.length&&c(e.nodeName.toLowerCase(),d.tags))){if(h=d.classes.length){h=d.classes;var m=b.attrValues(e,"className");h=a(h,m)}if(h=!h){if(h=d.rels.length)h=d.rels,m=b.attrValues(e,"rel"),h=c(e.nodeName.toLowerCase(),",a,")&&a(h,m);h=!h&&!("function"===b.type(d.custom)&&d.custom(e,f))}}return h},m=!f.self||g(e,!0);if(f.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!g(e,!1)){h=!1;break}return m&&h}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,f=-Infinity,h=-Infinity,m;for(a=0;a<c;a++)m=b.position(arguments[a]),d=Math.min(d,m.x),e=Math.min(e,m.y),f=Math.max(f,m.x+arguments[a].offsetWidth),h=Math.max(h,m.y+arguments[a].offsetHeight);return{x:d,y:e,w:f-d,h:h-e,x1:d,y1:e,x2:f,y2:h}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},indexOf:function(){return Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c)}:function(a,c){var b,e;b=0;for(e=a.length;b<e;b++)if(a[b]===c)return b;return-1}}(),isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var d=[];b.each(a,function(a,b){void 0!==a&&(d[b]=c(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,arguments)}catch(a){return!0}},on:function(){var a;return function(c,d,e){var f,h;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;e=d;d=c;c=a}try{f=c["on"+d]}catch(m){}"function"===typeof f&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=f.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));h=b.exceptionLogger(function(){if(a.enabled())return e.apply(null,arguments)});c.addEventListener?c.addEventListener(d,h,!1):c.attachEvent&&
c.attachEvent("on"+d,h)}}}(),position:function(a,c){var b,e=0,f=0,h=0,m=0;c=c||document;if(!a.offsetParent)return!1;b=a;do e+=b.offsetLeft,f+=b.offsetTop,b=b.offsetParent;while(b);b=a;do h+=b.scrollLeft,m+=b.scrollTop,b=b.parentNode;while(b&&b!==c.body);return{x:e-h,y:f-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(b,d){(null===b||void 0===b)&&delete a[d]});return a},ready:function(){var a=!1,c=[],d=!1,e,f,h,m,g;document.addEventListener?
h=function(){document.removeEventListener("DOMContentLoaded",h,!1);g()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),g())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return g();if(document.addEventListener)document.addEventListener("DOMContentLoaded",h,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&
c&&f()}b.on(window,"load",g)}};f=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.exceptionLogger(f),1);return}g()}};g=function(){if(!d){if(!document.body)return setTimeout(b.exceptionLogger(g),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reformatKeys:function(a){var c,d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=
a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,f=b.attrValues(a,"className");d=0;for(e=f.length;d<e;d++)f[d]===c&&delete f[d];a.className=f.join(" ")}},request:function(a,c,d){var e,f;d=b.extend({fn:b.noop,jsonp:!0,"return":!1,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],f=d.fn):"function"===typeof d.fn&&(!0!==d.jsonp?e=d.fn:(e=b.destructing(d.fn),f=b.uniqid("vglnk_jsonp_"),window[f]=b.exceptionLogger(function(){e.apply(this,arguments);window[f]=void 0}),
null!==d.timeout&&setTimeout(b.exceptionLogger(e),d.timeout)));f&&(c=b.extend({format:"jsonp",jsonp:f},c));c=b.toQuery(c);return d["return"]?a+(c.length?"?":"")+c:b.traits.cors&&b.cors(a,c,d.jsonp?null:e)?!0:b.jsonp(a+(c.length?"?":"")+c)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var d,e,f=[];d=0;for(e=a.length;d<e;d++)f[d]=a[d];return f}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},
toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},transmitsPII:function(a){return b.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});var q=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};q.amd=!0;(function(a){function b(a,
c,s,d){var e,h,f,m,g;(c?c.ownerDocument||c:F)!==A&&J(c);c=c||A;s=s||[];if(!a||"string"!==typeof a)return s;if(1!==(m=c.nodeType)&&9!==m)return[];if(G&&!d){if(e=ta.exec(a))if(f=e[1])if(9===m)if((h=c.getElementById(f))&&h.parentNode){if(h.id===f)return s.push(h),s}else return s;else{if(c.ownerDocument&&(h=c.ownerDocument.getElementById(f))&&U(c,h)&&h.id===f)return s.push(h),s}else{if(e[2])return K.apply(s,c.getElementsByTagName(a)),s;if((f=e[3])&&w.getElementsByClassName&&c.getElementsByClassName)return K.apply(s,
c.getElementsByClassName(f)),s}if(w.qsa&&(!z||!z.test(a))){h=e=y;f=c;g=9===m&&a;if(1===m&&"object"!==c.nodeName.toLowerCase()){m=u(a);(e=c.getAttribute("id"))?h=e.replace(ua,"\\$&"):c.setAttribute("id",h);h="[id='"+h+"'] ";for(f=m.length;f--;)m[f]=h+r(m[f]);f=da.test(a)&&n(c.parentNode)||c;g=m.join(",")}if(g)try{return K.apply(s,f.querySelectorAll(g)),s}catch(l){}finally{e||c.removeAttribute("id")}}}var k;a:{a=a.replace(X,"$1");h=u(a);if(!d&&1===h.length){e=h[0]=h[0].slice(0);if(2<e.length&&"ID"===
(k=e[0]).type&&w.getById&&9===c.nodeType&&G&&t.relative[e[1].type]){c=(t.find.ID(k.matches[0].replace(L,M),c)||[])[0];if(!c){k=s;break a}a=a.slice(e.shift().value.length)}for(m=Y.needsContext.test(a)?0:e.length;m--;){k=e[m];if(t.relative[f=k.type])break;if(f=t.find[f])if(d=f(k.matches[0].replace(L,M),da.test(e[0].type)&&n(c.parentNode)||c)){e.splice(m,1);a=d.length&&r(e);if(!a){K.apply(s,d);k=s;break a}break}}}ea(a,h)(d,c,!G,s,da.test(a)&&n(c.parentNode)||c);k=s}return k}function d(){function a(c,
d){b.push(c+" ")>t.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[y]=!0;return a}function f(a){var b=A.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function h(a,b){for(var c=a.split("|"),d=a.length;d--;)t.attrHandle[c[d]]=b}function m(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||la)-(~a.sourceIndex||la);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}
function g(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function k(a){return e(function(b){b=+b;return e(function(c,d){for(var e,h=a([],c.length,b),f=h.length;f--;)if(c[e=h[f]])c[e]=!(d[e]=c[e])})})}function n(a){return a&&typeof a.getElementsByTagName!==R&&a}function C(){}function u(a,d){var e,h,f,m,g,l,k;if(g=ma[a+" "])return d?0:g.slice(0);g=a;l=[];for(k=
t.preFilter;g;){if(!e||(h=va.exec(g)))h&&(g=g.slice(h[0].length)||g),l.push(f=[]);e=!1;if(h=wa.exec(g))e=h.shift(),f.push({value:e,type:h[0].replace(X," ")}),g=g.slice(e.length);for(m in t.filter)if((h=Y[m].exec(g))&&(!k[m]||(h=k[m](h))))e=h.shift(),f.push({value:e,type:m,matches:h}),g=g.slice(e.length);if(!e)break}return d?g.length:g?b.error(a):ma(a,l).slice(0)}function r(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function fa(a,b,c){var d=b.dir,e=c&&"parentNode"===d,h=xa++;return b.first?
function(b,c,s){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,s)}:function(b,c,s){var f,D,m,g=H+" "+h;if(s)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,s))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(m=b[y]||(b[y]={}),(D=m[d])&&D[0]===g){if(!0===(f=D[1])||f===Z)return!0===f}else if(D=m[d]=[g],D[1]=a(b,c,s)||Z,!0===D[1])return!0}}function ga(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function $(a,b,c,d,e){for(var h,f=[],m=0,g=a.length,
l=null!=b;m<g;m++)if(h=a[m])if(!c||c(h,d,e))f.push(h),l&&b.push(m);return f}function ha(a,d,s,h,f,m){h&&!h[y]&&(h=ha(h));f&&!f[y]&&(f=ha(f,m));return e(function(e,m,g,l){var k,p,n=[],C=[],B=m.length,v;if(!(v=e)){v=d||"*";for(var x=g.nodeType?[g]:g,t=[],u=0,E=x.length;u<E;u++)b(v,x[u],t);v=t}v=a&&(e||!d)?$(v,n,a,g,l):v;x=s?f||(e?a:B||h)?[]:m:v;s&&s(v,x,g,l);if(h){k=$(x,C);h(k,[],g,l);for(g=k.length;g--;)if(p=k[g])x[C[g]]=!(v[C[g]]=p)}if(e){if(f||a){if(f){k=[];for(g=x.length;g--;)if(p=x[g])k.push(v[g]=
p);f(null,x=[],k,l)}for(g=x.length;g--;)if((p=x[g])&&-1<(k=f?P.call(e,p):n[g]))e[k]=!(m[k]=p)}}else x=$(x===m?x.splice(B,x.length):x),f?f(null,m,x,l):K.apply(m,x)})}function ia(a){var b,c,d,e=a.length,h=t.relative[a[0].type];c=h||t.relative[" "];for(var f=h?1:0,g=fa(function(a){return a===b},c,!0),m=fa(function(a){return-1<P.call(b,a)},c,!0),l=[function(a,c,d){return!h&&(d||c!==aa)||((b=c).nodeType?g(a,c,d):m(a,c,d))}];f<e;f++)if(c=t.relative[a[f].type])l=[fa(ga(l),c)];else{c=t.filter[a[f].type].apply(null,
a[f].matches);if(c[y]){for(d=++f;d<e&&!t.relative[a[d].type];d++);return ha(1<f&&ga(l),1<f&&r(a.slice(0,f-1).concat({value:" "===a[f-2].type?"*":""})).replace(X,"$1"),c,f<d&&ia(a.slice(f,d)),d<e&&ia(a=a.slice(d)),d<e&&r(a))}l.push(c)}return ga(l)}function ya(a,d){var h=0,f=0<d.length,g=0<a.length,m=function(e,m,l,k,p){var n,v,C,x=0,B="0",u=e&&[],E=[],w=aa,r=e||g&&t.find.TAG("*",p),z=H+=null==w?1:Math.random()||0.1,q=r.length;p&&(aa=m!==A&&m,Z=h);for(;B!==q&&null!=(n=r[B]);B++){if(g&&n){for(v=0;C=
a[v++];)if(C(n,m,l)){k.push(n);break}p&&(H=z,Z=++h)}f&&((n=!C&&n)&&x--,e&&u.push(n))}x+=B;if(f&&B!==x){for(v=0;C=d[v++];)C(u,E,m,l);if(e){if(0<x)for(;B--;)!u[B]&&!E[B]&&(E[B]=za.call(k));E=$(E)}K.apply(k,E);p&&(!e&&0<E.length&&1<x+d.length)&&b.uniqueSort(k)}p&&(H=z,aa=w);return u};return f?e(m):m}var S,w,Z,t,ba,na,ea,aa,N,T,J,A,I,G,z,Q,ca,U,y="sizzle"+-new Date,F=a.document,H=0,xa=0,oa=d(),ma=d(),pa=d(),ja=function(a,b){a===b&&(T=!0);return 0},R="undefined",la=-2147483648,Aa={}.hasOwnProperty,O=[],
za=O.pop,Ba=O.push,K=O.push,qa=O.slice,P=O.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},ra="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),sa="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+ra+")|)|)[\\x20\\t\\r\\n\\f]*\\]",ka=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+sa.replace(3,8)+")*)|.*)\\)|)",
X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,va=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,wa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ca=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Da=RegExp(ka),Ea=RegExp("^"+ra+"$"),Y={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+sa),PSEUDO:RegExp("^"+ka),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},Fa=/^(?:input|select|textarea|button)$/i,Ga=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,ta=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,ua=/'|\\/g,L=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,
M=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{K.apply(O=qa.call(F.childNodes),F.childNodes),O[F.childNodes.length].nodeType}catch(Ha){K={apply:O.length?function(a,b){Ba.apply(a,qa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}w=b.support={};na=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};J=b.setDocument=function(a){var b=a?a.ownerDocument||
a:F;a=b.defaultView;if(b===A||9!==b.nodeType||!b.documentElement)return A;A=b;I=b.documentElement;G=!na(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){J()},!1):a.attachEvent&&a.attachEvent("onunload",function(){J()}));w.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});w.getElementsByTagName=f(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});w.getElementsByClassName=V.test(b.getElementsByClassName)&&
f(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});w.getById=f(function(a){I.appendChild(a).id=y;return!b.getElementsByName||!b.getElementsByName(y).length});w.getById?(t.find.ID=function(a,b){if(typeof b.getElementById!==R&&G){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},t.filter.ID=function(a){var b=a.replace(L,M);return function(a){return a.getAttribute("id")===b}}):(delete t.find.ID,
t.filter.ID=function(a){var b=a.replace(L,M);return function(a){return(a=typeof a.getAttributeNode!==R&&a.getAttributeNode("id"))&&a.value===b}});t.find.TAG=w.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==R)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,h=b.getElementsByTagName(a);if("*"===a){for(;c=h[e++];)1===c.nodeType&&d.push(c);return d}return h};t.find.CLASS=w.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==R&&G)return b.getElementsByClassName(a)};
Q=[];z=[];if(w.qsa=V.test(b.querySelectorAll))f(function(a){a.innerHTML="<select t=''><option selected=''></option></select>";a.querySelectorAll("[t^='']").length&&z.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||z.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||z.push(":checked")}),f(function(a){var c=b.createElement("input");
c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&z.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||z.push(":enabled",":disabled");a.querySelectorAll("*,:x");z.push(",.*:")});(w.matchesSelector=V.test(ca=I.webkitMatchesSelector||I.mozMatchesSelector||I.oMatchesSelector||I.msMatchesSelector))&&f(function(a){w.disconnectedMatch=ca.call(a,"div");ca.call(a,"[s!='']:x");Q.push("!=",ka)});z=z.length&&RegExp(z.join("|"));
Q=Q.length&&RegExp(Q.join("|"));U=(a=V.test(I.compareDocumentPosition))||V.test(I.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ja=a?function(a,c){if(a===c)return T=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===
(c.ownerDocument||c)?a.compareDocumentPosition(c):1;return d&1||!w.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===F&&U(F,a)?-1:c===b||c.ownerDocument===F&&U(F,c)?1:N?P.call(N,a)-P.call(N,c):0:d&4?-1:1}:function(a,c){if(a===c)return T=!0,0;var d,e=0;d=a.parentNode;var h=c.parentNode,f=[a],W=[c];if(!d||!h)return a===b?-1:c===b?1:d?-1:h?1:N?P.call(N,a)-P.call(N,c):0;if(d===h)return m(a,c);for(d=a;d=d.parentNode;)f.unshift(d);for(d=c;d=d.parentNode;)W.unshift(d);for(;f[e]===W[e];)e++;
return e?m(f[e],W[e]):f[e]===F?-1:W[e]===F?1:0};return b};b.matches=function(a,d){return b(a,null,null,d)};b.matchesSelector=function(a,d){(a.ownerDocument||a)!==A&&J(a);d=d.replace(Ca,"='$1']");if(w.matchesSelector&&G&&(!Q||!Q.test(d))&&(!z||!z.test(d)))try{var e=ca.call(a,d);if(e||w.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(h){}return 0<b(d,A,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==A&&J(a);return U(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==A&&J(a);var c=t.attrHandle[b.toLowerCase()],c=c&&Aa.call(t.attrHandle,b.toLowerCase())?c(a,b,!G):void 0;return void 0!==c?c:w.attributes||!G?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;T=!w.detectDuplicates;N=!w.sortStable&&a.slice(0);a.sort(ja);if(T){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}N=null;return a};ba=b.getText=
function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=ba(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=ba(b);return c};t=b.selectors={cacheLength:50,createPseudo:e,match:Y,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(L,
M);a[3]=(a[4]||a[5]||"").replace(L,M);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(Y.CHILD.test(a[0]))return null;if(a[3]&&void 0!==a[4])a[2]=a[4];else if(c&&Da.test(c)&&(b=u(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(L,M).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=oa[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&oa(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==R&&a.getAttribute("class")||"")})},ATTR:function(a,d,e){return function(h){h=b.attr(h,a);if(null==
h)return"!="===d;if(!d)return!0;h+="";return"="===d?h===e:"!="===d?h!==e:"^="===d?e&&0===h.indexOf(e):"*="===d?e&&-1<h.indexOf(e):"$="===d?e&&h.slice(-e.length)===e:"~="===d?-1<(" "+h+" ").indexOf(e):"|="===d?h===e||h.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,b,c,d,e){var h="nth"!==a.slice(0,3),f="last"!==a.slice(-4),m="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,g){var l,k,p,s,D;c=h!==f?"nextSibling":"previousSibling";var n=b.parentNode,v=m&&b.nodeName.toLowerCase();
g=!g&&!m;if(n){if(h){for(;c;){for(k=b;k=k[c];)if(m?k.nodeName.toLowerCase()===v:1===k.nodeType)return!1;D=c="only"===a&&!D&&"nextSibling"}return!0}D=[f?n.firstChild:n.lastChild];if(f&&g){g=n[y]||(n[y]={});l=g[a]||[];s=l[0]===H&&l[1];p=l[0]===H&&l[2];for(k=s&&n.childNodes[s];k=++s&&k&&k[c]||(p=s=0)||D.pop();)if(1===k.nodeType&&++p&&k===b){g[a]=[H,s,p];break}}else if(g&&(l=(b[y]||(b[y]={}))[a])&&l[0]===H)p=l[1];else for(;k=++s&&k&&k[c]||(p=s=0)||D.pop();)if((m?k.nodeName.toLowerCase()===v:1===k.nodeType)&&
++p)if(g&&((k[y]||(k[y]={}))[a]=[H,p]),k===b)break;p-=e;return p===d||0===p%d&&0<=p/d}}},PSEUDO:function(a,d){var h,f=t.pseudos[a]||t.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return f[y]?f(d):1<f.length?(h=[a,a,"",d],t.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var c,e=f(a,d),h=e.length;h--;)c=P.call(a,e[h]),a[c]=!(b[c]=e[h])}):function(a){return f(a,0,h)}):f}},pseudos:{not:e(function(a){var b=[],c=[],d=ea(a.replace(X,"$1"));return d[y]?e(function(a,b,c,e){e=
d(a,null,e,[]);for(var h=a.length;h--;)if(c=e[h])a[h]=!(b[h]=c)}):function(a,e,h){b[0]=a;d(b,null,h,c);return!c.pop()}}),has:e(function(a){return function(d){return 0<b(a,d).length}}),contains:e(function(a){return function(b){return-1<(b.textContent||b.innerText||ba(b)).indexOf(a)}}),lang:e(function(a){Ea.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(L,M).toLowerCase();return function(b){var c;do if(c=G?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),
c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===I},focus:function(a){return a===A.activeElement&&(!A.hasFocus||A.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},
selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Ga.test(a.nodeName)},input:function(a){return Fa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==
(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:k(function(){return[0]}),last:k(function(a,b){return[b-1]}),eq:k(function(a,b,c){return[0>c?c+b:c]}),even:k(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:k(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:k(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:k(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};t.pseudos.nth=t.pseudos.eq;for(S in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[S]=
g(S);for(S in{submit:!0,reset:!0})t.pseudos[S]=l(S);C.prototype=t.filters=t.pseudos;t.setFilters=new C;ea=b.compile=function(a,b){var c,d=[],e=[],h=pa[a+" "];if(!h){b||(b=u(a));for(c=b.length;c--;)h=ia(b[c]),h[y]?d.push(h):e.push(h);h=pa(a,ya(e,d))}return h};w.sortStable=y.split("").sort(ja).join("")===y;w.detectDuplicates=!!T;J();w.sortDetached=f(function(a){return a.compareDocumentPosition(A.createElement("div"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||
h("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!w.attributes||!f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&h("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||h("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof q&&q.amd?q(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.platforms=function(){var a={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},
ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}};return function(c){return b.extend(a[c]||{},
{getPostIDs:function(){var a=[],c=this.id_finder;c&&b.each(b.select(c[0]),function(b){var h=c[2]||"id";(b=b[h]?b[h].match(c[1]):null)&&a.push(b[1])});return a.length?a:null}})}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||
!(b.browser.ie||b.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var l,n,r;g={PLUGIN_MANUAL:1,api:function(){var a=function(a,c,f){f=f||{};c=b.extend(g.commonParams(a),c);c.subId&&c.key!==l.key&&(c.subId=null);return{method:a,opts:f,params:c}},c=function(a){return b.request(l.api_url+"/"+a.method,a.params,a.opts)};return b.batchable({batch:function(){var d=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var e,g=c[d];a&&g&&
("domains"===d&&"array"===b.type(a)&&(a={results:a}),a="string"===b.type(a)&&(e=a.match(/^\s*\w+\((.*)\);?\s*$/))?b.fromJSON("["+e[1]+"]")||{}:[a],g.apply(window,a))})};return function(e){var f={},h={};b.each(e,function(c){c=a.apply(this,c);h[c.method]=c.opts.fn||b.noop;f[c.method]=b.prune(c.params)});c({method:"batch",params:b.extend(g.commonParams(),{batch:window.JSON.stringify(f)}),opts:{jsonp:!1,fn:function(a){d(a,h)}}})}}(),single:function(b,e,f){b=a(b,e,f);return c(b)}})}(),addEventListener:function(a,
b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var f=a.open("",c);f.focus();return f}},c=function(a){var c=a.previousSibling,f=a.nextSibling,h=["",a.textContent,""],m=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},l=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),
a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==h[1]&&(h[0]=c&&3===c.nodeType?m(c,"previous"):"",h[2]=f&&3===f.nodeType?m(f,"next"):"",h=l.apply(this,h),""!==h[0]&&""!==h[2]&&(h[0]=h[0].split(" ").reverse().slice(0,10+(" "===h[0].substr(h[0].length-1,1)?1:0)).reverse().join(" "),h[2]=h[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,
before:h[0],after:h[2],txt:h[1],loc:location.href,out:b.getActualHref(a),v:2},g.log("info",b.toQuery(a))))};return function(d,e){var f,h,g,k,p=b.context(d)||window;e=d.target||e;e=!e||e===p.name||"_top"===e&&p.top===p||"_parent"===e&&p.parent===p?"_self":e;g=a(p,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))k="go";else try{if(void 0===g.document)throw!0;k="jsonp"}catch(n){k="go"}f=b.destructing(b.bind(function(){l.time_click&&arguments.length&&this.logTime("clk");
var a=b.toArray(arguments);a.unshift(d,g,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!l.enabled)return f();h=this.clickParams(d,k);this.logTime();l.log_context&&c(d);if("go"===k)this.redirect(this.api.now("click",h,{"return":!0}),p,g,e);else if(g===p)this.api.now("click",h,{fn:f,timeout:l.click_timeout});else{if(b.contextIsAncestor(p,g))return this.redirect(b.getActualHref(d),
p,g,e);f=b.exceptionLogger(f);setTimeout(function(){f()},l.click_timeout);g.document.open();g.callback=f;g.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",h,{fn:"callback","return":!0})+'">\x3c/script></head></html>');g.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:l.reaffiliate||null,title:window.document.title,txt:a.innerHTML});
128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:l.key?null:l.dr_key,key:l.key,libId:l.library_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:l.cuid,loc:location.href,subId:l.sub_id,v:1},c);return c},enabled:function(){if(l.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))l.enabled=!1;return l.enabled},expose:function(a,c){if(c=c||this[a])"function"===
typeof c?c=b.exceptionLogger(b.bind(c,this)):"object"===typeof c&&(c=b.clone(c)),r[a]||(r[a]=c)},fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,c){if(l.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,
"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return l.harmony_level<=a}}(),init:b.exceptionLogger(function(){return function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),
this.initNamespace(),this.initOptions(),b.exceptionLogger(b.bind(this.logException,this),!l.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}}()),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);r=n[k]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",
b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return g.registerProcessor.apply(g,arguments)});b.extend(r,r===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){a=!0;l.dr_key=
window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:g.onClick,right:g.onContextmenu},d={left:b.noop,right:b.noop},e=b.traits.windowLevelHandlers?a:a.document,f=function(e){e=e||a.event;if((e=b.eventLink(e))&&!b.cache(e,"evented"))h(e,g.harmony(b.harmony.LINK_LEVEL_EVENTS)?c:d),b.cache(e,"evented",!0)},h=function(a,c){b.on(a,"click",b.bind(c.left,g));b.on(a,"contextmenu",
b.bind(c.right,g))};b.on(e,"copy",b.bind(g.onCopy,g));b.on(e,"mousedown",f);if(g.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",f)})});(!b.traits.quirksMode||g.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&h(e,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(r[b[a]]=window[a],"vglnk_domain"===
a&&(r[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){l.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(g);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(k="vglnk");var a=window,b=
k.split("."),d;for(k=b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];n=a;r=n[k]=n[k]||{}},initOptions:function(){var a;this.initLegacyOptions();l=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),l,r,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,
nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in l)"_plugin"===a.substr(-7)&&delete l[a]},initPlugins:function(){var a,c=1,d={},e={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=function(b){return function(b){return function(){delete d[b].opts.mode;c=1;clearTimeout(a);h()}}(b)},h=function(){var e=!1,f={},m=
function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);g.log.apply(this,c)}}};a=null;b.each(d,function(a,c){a.setup=a.setup||window.vglnk&&window.vglnk[c+"_plugin"];a.setup?(!a.run&&"function"===b.type(a.setup)&&(a.run=a.setup(a.opts,b.clone(b),r,m(a.opts.key||l.key))||b.noop),a.opts.mode===g.PLUGIN_MANUAL?f[c]=a:a.run()):(e=!0,f[c]=a)});d=f;e&&(a=setTimeout(b.exceptionLogger(h),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},m=function(){setTimeout(function(){g.api.flush()},
100);h();b.on("DOMReady",function(){setTimeout(g.api.flush,0)})};return function(a){b.each(a,b.bind(function(a,b){b=e[b]||b;"object"===typeof a&&!1!==a.enabled&&(d[b]={opts:a},a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,f(b)))},this));m()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(l.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=
c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){l.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["norewrite","noskim"],custom:function(c){var e,
f="";try{e=c.hostname,f=c.protocol,e.charAt(0)}catch(h){return!0}""!==e&&(e=b.canonicalizeHostname(c));return""===e||a===e||"object"===b.type(l.commercial)&&!l.commercial[e]||!f.match(/^https?:$/i)||l.norewrite[e]||!(l.rewrite_original||b.cache(c,"type"))}});return function(a){return c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var f,h=b.toQuery({libId:l.library_id,nocache:b.uniqid()});f="pixel.gif";if("custom"===a)h+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],function(a){b.each(["e",
"i","o"],function(b){delete a[b]});h+="&"+b.toQuery(a)});else{h+="&"+b.toQuery({key:l.key,drKey:l.key?null:l.dr_key});if("time"===a)f="time.gif",a={time:d,type:c};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;h+="&"+b.toQuery(a)}f=l.api_url+"/"+f+"?"+h;b.transmitsPII(f)||(b.createEl("img").src=f)},logException:function(a){if(l.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",
a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,d,e,f){var h=e||b.getActualHref(a),g=b.bind(function(){this.redirect(h,b.context(a),c,d)},this);"object"===typeof f&&(f.tracking||f.image)?(e=b.createEl(f.tracking?"iframe":"img",{src:f.tracking||f.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),setTimeout(b.exceptionLogger(g),f.timeout||l.hop_timeout)):
g()},onApiPing:function(a,c,d,e,f,h){l.rewrite_original=!1;f=b.reformatKeys(f||{});var m,k;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};k=b.extend(l.plugins,f.plugins);l=b.extend(l,f);delete l.plugins;l.library_id=a;l.click_timeout=c;l.time_ping&&this.logTime("png");"array"===b.type(l.testing_js)&&0<l.testing_js.length&&b.each(l.testing_js,function(a){b.jsonp(a)});b.extend(l.norewrite,e(d));b.extend(l.nofollow,e(h));for(m in l)"on"===m.toLowerCase().substr(0,
2)&&(2<m.length&&"function"===b.type(l[m]))&&(b.on(g,m.toLowerCase().substr(2),b.bind(l[m],window)),delete l[m]);this.initPlugins(k);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=b.eventLink(a);if(e&&this.isRewritable(e)&&!c&&d&&!b.isDefaultPrevented(a))return this.click(e),b.preventDefault(a)},onContextmenu:function(a){(a=b.eventLink(a||window.event))&&this.isRewritable(a)&&
this.handleRightClick(a,"setup")},onCopy:function(a){var c,d,e,f=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(h){}0<e.length&&128>=e.length&&f.push(e)}}b.each(f,function(a){g.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(l[a]=b);return l[a]},ping:function(){var a=!1;return function(){if(!a&&
(l.key||l.dr_key)){var c={ref:document.referrer||null};a=!0;b.transmitsPII(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)}))}}}(),processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a}},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,
c,d,e){!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.exceptionLogger(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},registerProcessor:function(){var a=!1,c=[],d=function(d){if(void 0===d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),
fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};g.init();try{delete window.vglnk_self}catch(u){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(k,g,b){var q={},l;k=g.extend({any:!0},k);l={getDomains:function(){var k=[];g.each(q,function(b,g){k.push(g)});0<k.length&&b.api("domains",{domains:k.join("|")},{fn:g.bind(l.onDomainApi,l)})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,g.on("DOMReady",g.bind(this.getDomains,this)))}}(),onDomainApi:function(l){var k;"object"===g.type(l)&&"array"===g.type(l.results)&&(k={},g.each(l.results,function(b){k[b]=!0}),b.opt("commercial",k))},saveDomain:function(b){b=
g.canonicalizeHostname(b);q[b]=!0},setup:function(){b.opt("rewrite_original",!0);k.any||b.registerProcessor(function(b){l.initDomainLookup();l.saveDomain(b)})}};return function(){l.setup()}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(k,g,b){return function(){b.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(k,g){var b="https:"===document.location.protocol,q={setup:function(){window._comscore=window._comscore||[]},run:function(){var l=window._comscore;l&&"function"===g.type(l.push)&&(l.push({c1:8,c2:17570528,c3:1}),g.jsonp("//"+(b?"sb":"b")+".scorecardresearch.com/beacon.js"))}};q.setup();return function(){q.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(k,g,b){k=g.extend({key:null},k);var q={init:function(){g.each(this.getDRSearchForms(),function(b){if(!g.cache(b,"evented")){var k=q.getInput(b),r=function(){k.value||g.css(k,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};g.cache(b,"evented",!0);b.onsubmit=null;k.onfocus=null;k.onblur=null;g.on(k,"focus",function(){g.css(k,{"background-image":"none"})});g.on(k,"blur",r);r();g.on(b,"submit",function(g){q.onSubmit(g,b)})}})},
getDRSearchForms:function(){var b=[];g.each(document.getElementsByTagName("form"),function(g){q.getInput(g)&&g.id.match(/^DR-ebay-search(CSS|2)?$/i)&&b.push(g)});return b},getInput:function(b){return b.p||b.q2},onSubmit:function(l,n){l=l||window.event;var r="http://shop.ebay.com/i.html?"+g.toQuery({_nkw:q.getInput(n).value}),r=g.createA(r,"_blank");g.cache(r,"params",{key:k.key});b.click(r);return g.preventDefault(l)}};return function(){k.key&&(q.init(),g.on("DOMReady",g.bind(q.init,q)))}};
window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(k,g,b,q){var l,n={},r=0;k=g.extend({platform:null},k);l={getLinks:function(){var n=g.platforms(k.platform).getPostIDs();b.api("optimize",{pt:k.platform,i:n?n.join("|"):null,u:location.href},{fn:g.bind(l.onOptimizeApi,l)})},log:function(){q("optimize",{ct:r})},onOptimizeApi:function(b){"object"===g.type(b)&&"object"===g.type(b.optLinks)&&(n=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var b=g.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],
custom:function(a,b){if(b)return Boolean(g.cache(a,"type"))}}),a=function(a){var b=a.href,e=a.textContent||a.innerText,f=function(){var b=g.canonicalizeHostname(a);return g.canonicalizeHostname(g.createEl("a",{href:e}))===b},h=function(){var b;return f()?(b=g.fromQuery(a.search),g.find(b,function(a){return a===e})):!1};return{exact:b===e||function(){var a=e.replace(/(\.\.\.|\u2026)$/,"");return a===e?!1:b.substr(0,a.length)===a}()||h(),partial:function(){var b=g.canonicalizeHostname(a);return RegExp("\\b"+
g.escapeRegExp(b)+"\\b","i").test(e)}()||-1!==e.indexOf(b)}};return function(c){var d,e=n[c.href];if(e&&b(c)){d=a(c);if(d.exact){d=e.frdLink||e.optLink;for(var f;f=c.firstChild;)c.removeChild(f);c.appendChild(document.createTextNode(d))}else if(d.partial)return;g.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink;r++}}}(),optimizeLinks:function(){var k={data:!1,timing:!1};return function(a){k=g.extend(k,a);k.timing&&(k.data&&n)&&(b.registerProcessor(g.bind(this.optimizeLink,
l)),setTimeout(function(){l.log()},0))}}(),setup:function(){if(!k.platform||"full"===k.platform)this.getLinks();else g.on("DOMReady",g.bind(this.getLinks,this))}};l.setup();return function(){g.on("DOMReady",function(){l.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(k,g,b){k=g.extend({level:null},k);return function(){var g=parseInt(k.level,10);isFinite(g)&&b.opt("harmony_level",g)}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(k,g,b,q){var l,n,r=null,u={},a,c=0,d=0,e=0,f=0;k=g.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},k);if(k.key)return l=g.platforms(k.platform),n={addPhrasesToMatcher:function(b){var c="";"regexp"===g.type(b)?c=b.source:"array"===g.type(b)&&(c="(?:^|[\\s\"'\\(])("+g.map(b,g.escapeRegExp).join("|")+")(?=\\s|\\W*$|\\W{2})");
""!==c&&(a=RegExp(a?"(?:"+c+"|"+a.source+")":c,"i"))},focusLink:function(a){a.id||(a.id=g.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(){var a=l.getPostIDs();b.api("insert",g.extend(n.getPartnerParams(),{cat:k.cat,mode:k.mode,pt:k.platform,ps:k.product_source,i:a?a.join("|"):null,u:location.href,type:k.type}),{fn:g.bind(n.onInsertApi,n)})},getPartnerParams:function(){var a,c,d=b.opt("partner"),e={};for(a in d)break;if(a)for(c in d[a])e[a+"_"+c]=d[a][c];
return e},initLink:function(a,c,d){if(d=k.link_target||d)a.target=d;a.rel="nofollow";a.href||(a.href=c.url);g.cache(a,"params",{exp:r,key:k.key,mid:c.mid,type:c.type||null});g.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var b={data:k.link_phrases?!1:k.link_urls,timing:!1},l=function(a,b){var c;c=g.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";g.cache(c,"type","inserted");g.cache(c,"phrase",a);k.ui&&(c.title="Link added by VigLink");
n.initLink(c,b);return c},r=function(b,h){for(var p,n,r,q,v=function(a){var b;a=!a||!k.per_phrase||!a.count||a.count<k.per_phrase;b=!k.per_page||c<k.per_page;return a&&b},B=function(a,b){var c,d,e,f,h,l,m,p,n,q,r=function(b){n.parentNode.insertBefore(a,n);n.parentNode.removeChild(n);return b},v=function(a,b,c){a=g.extend({},a);a.x1-=c;a.y1-=c;a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};n=g.createEl("span");a.parentNode.insertBefore(n,a);n.appendChild(a);q=g.geometry(n);if(k.proximity||
k.same_proximity)for(l in u)if((m=u[l].links)&&!(u[l]===b&&!k.same_proximity||u[l]!==b&&!k.proximity)){p=u[l]===b?Math.max(k.same_proximity,k.proximity):k.proximity;c=0;for(d=m.length;c<d;c++){h=m[c].segments;e=0;for(f=h.length;e<f;e++)if(v(h[e].geometry,q,p))return r(!1)}}return r(!0)},E=function(a,b){var c,d,e,f,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===f||e.offsetTop===f.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),f=
e;l.geometry=g.geometry.apply(g,l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};b&&b.data&&(Boolean(r=b.data.match(/^\s+/))||Boolean(r=b.data.match(a)));)n=r[0],q=r.slice(1).join(""),p=u[q.toLowerCase()],n=b.data.indexOf(n)+n.length-q.length,0<n&&(b=b.splitText(n)),n=b.length<=q.length?null:b.splitText(q.length),q&&!p&&(p={url:q.match(/^https?:\/\//i)?q:"http://"+q,type:"U"}),q&&(v(p)&&B(b,p))&&(q=l(q,p),g.cache(q,"unlinked")||("U"===p.type?f++:"L"===p.type.toUpperCase()?d++:
e++,h(q,b),E(q,p),p.count++,c++)),b=n},p=function(b){var c=!1,d=b.parentNode,e=function(a,b){d.insertBefore(a,b);d.removeChild(b)};b.data&&(c=a.test(b.data.replace(/\s+/," ")));c&&r(b,e)},q=g.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return g.matches(a,"a[href]")}}),v=function(a){var b;if(a){if(q(a,{ancestors:!1,self:!0}))for(b=
a.firstChild;b;)a=b.nextSibling,1===b.nodeType?v(b):3===b.nodeType&&p(b),b=a}else g.each(g.select(k.scope),function(a){q(a,{ancestors:!0,self:!1})&&v(a)})};return function(c){b=g.extend(b,c);b.timing&&(b.data&&a)&&(v(),n.log())}}(),loadPhrases:function(a){var b,c,d,e=[];b=0;for(c=a.length;b<c;b++)d=a[b],d.phrase&&d.url&&(d.phrase=d.phrase.toLowerCase(),u[d.phrase]||(e.push(d.phrase),u[d.phrase]={count:u[d.phrase]?u[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||""}));0<e.length&&
this.addPhrasesToMatcher(e);this.insertLinks({data:!0})},log:function(){var a,b,g={heavy:[],lite:[]},k=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(a in u)b=parseInt(u[a].count,10),0<b&&(b=[b,a.replace(/\|/g,"%7C")].join(),g["L"===u[a].type.toUpperCase()?"lite":"heavy"].push(b));g.lite.sort(k);g.heavy.sort(k);q("insert",[{ct:c,cl:d,ch:e,cu:f,exp:r},{pl:g.lite.join("|")},{ph:g.heavy.join("|")}])},onInsertApi:function(a){"object"===g.type(a)&&(r=a.exp,a.results&&this.loadPhrases(a.results))},
setup:function(){k.scope=k.scope||l.scope||"body";k.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"));if(k.link_phrases)if(!k.platform||"full"===k.platform)this.getPhrases();else g.on("DOMReady",g.bind(this.getPhrases,
this))}},n.setup(),function(){g.on("DOMReady",function(){n.insertLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(k,g,b){window.vglnk.spotlight_plugin.exports={$:g,opts:k,vglnk:b};return function(){(!g.browser.ie||6<g.browser.version)&&g.jsonp(b.opt("asset_url")+"/spotlight.js")}};